name: Deuxième test - CI

on:
  workflow_dispatch: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Action de contrôle du code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    # Le deploy à besoin du build (job2 need job1)
    needs: build
    # Condition: exécute ce job seulement si le job 'build' a réussi
    if: success()  

    steps:
      - name: Deploy to production
        run: echo "Déploiement de l'application en production..."

  notify:
    runs-on: ubuntu-latest
    needs: build
     # Condition: exécute ce job seulement si le job 'build' a échoué
    if: failure() 

    steps:
      - name: Notify failure
        run: echo "Les tests ont échoué. Notification envoyée."
