name: Premier WorkFlow

# Déclencheur du worflow (peut y en avoir plusieurs)
on:
  # Déclenche le WF manuellement
  workflow_dispatch: 

  # Déclenche le WF quand il y a une action push sur la main
  push: 
    branches: ["master"]

  # Déclenche le WF quand il y a une action pull-request sur la main
  pull_request:
    branches: ["master"]
# Lister et définir les différents travaux
jobs: 
  nom_job1:
    # L'OS de du Runner
    runs-on: ubuntu-latest

    # Liste des étapes à exécuter par le job 1
    steps: 
      - name: Première opération
        run: echo "Hello GitHub Action !"
      
      - name: Seconde opération
        run: echoo "Test avec une mauvaise instruction"
      
      - name: Troisième opération
        run: echo "Bye GitHub Action !"
